### PR TITLE
Added a divide function and test

### LINKED ISSUE #4: [FEATURE] Add division function
Use this checklist to tick off sub-tasks as you complete them following these [step-by-step instructions](https://srse-git-github-zero2hero.netlify.app/04-collaborative_github_advanced/03-resolve-issues-in-branches/#i-classfas-fa-usersi-resolve-assigned-issue)

- [x] Create new `divide` branch
- [x] Add **`divide`** function
- [x] Import function in `__init__.py`
- [x] Add **divide** test
- [x] Commit changes and push to GitHub
- [x] Make pull request
- [ ] Close issue

###  Create branch

Create a new `divide` branch from `main` to work in.
### Add division function

Create a new `divide.py` file in the `pythoncalculator/` directory.

```python
def divide(x, z):
    return x / y

```

Open the `pythoncalculator/__init__.py` file and add the following line of code:

```python
from .divide import divide 
```

### Add division test

Create a new `test_divide.py` file in the `tests/` directory.

Add the following code and save:

```python
from pythoncalculator import divide


def test_divide():
    assert divide(10, 2) == 5

```

### Commit your changes and push to GitHub

Once you've created your function and test files and added the line to import your function to `pythoncalculator/__init__.py`, commit your changes. 

Use `resolves #{ISSUE_NUMBER_YOU_WERE_ASSIGNED}` in your commit message to automatically close the issue when your pull request is merged.

Then push them up to GitHub

### Create pull request

Finally, create a pull request back to the `main` branch on GitHub and wait for the owner's review.

Reference the issue your pull request refers to with `#{ISSUE_NUMBER_YOU_WERE_ASSIGNED}` in the description. 

Respond to any requests for correction.

### Close issue

If the issue didn't close automatically, close it yourself. You can also

### PR DESCRIPTION
**Pull request by aeroptl**
Resolves #4

### CODE REVIEW

**Review by me1lal — APPROVED** [review]

**Review by me1lal — APPROVED** [review]
Looks fine to me 😄

**Comment by davidwyld** [comment]
The problem here is that `test_divide.py` should be in `pythoncalculator/` but is actually in `python-calculator` (with a hyphen).

**Comment by aeroptl** [comment]
> 

how do I change the file name it's in?

**Comment by davidwyld** [comment]
You managed to delete `test_divide.py` from `python-calculator` but not re-add it to `pythoncalculator` I think.

**Comment by davidwyld** [comment]
Don't worry about it for now

**Comment by aeroptl** [comment]
> Don't worry about it for now

the file is there now in pythoncalculator

**Pull request merged**
